import asyncio
import logging
import os
import platform
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from app.config import settings

logger = logging.getLogger(__name__)


def _find_begin_document(content: str) -> int | None:
    """Find the char offset of the *real* ``\\begin{document}`` (not inside a comment).

    Returns ``None`` if no uncommented ``\\begin{document}`` exists.
    """
    for m in re.finditer(r'\\begin\{document\}', content):
        line_start = content.rfind('\n', 0, m.start()) + 1
        prefix = content[line_start:m.start()]
        if '%' not in prefix:
            return m.start()
    return None


@dataclass
class CompileResult:
    success: bool = False
    pdf_path: str = ""
    log: str = ""
    errors: list[str] = field(default_factory=list)


_UNICODE_REPLACEMENTS = {
    "≥": r"$\geq$",
    "≤": r"$\leq$",
    "≠": r"$\neq$",
    "±": r"$\pm$",
    "×": r"$\times$",
    "÷": r"$\div$",
    "∞": r"$\infty$",
    "√": r"$\sqrt{}$",
    "α": r"$\alpha$",
    "β": r"$\beta$",
    "γ": r"$\gamma$",
    "δ": r"$\delta$",
    "θ": r"$\theta$",
    "λ": r"$\lambda$",
    "μ": r"$\mu$",
    "π": r"$\pi$",
    "σ": r"$\sigma$",
    "φ": r"$\varphi$",
    "ω": r"$\omega$",
    "°": r"$^\circ$",
    "²": r"$^2$",
    "³": r"$^3$",
    "⁻": r"$^-$",
    "⁷": r"$^7$",
    "₂": r"$_2$",
    "₃": r"$_3$",
    "→": r"$\rightarrow$",
    "←": r"$\leftarrow$",
    "↔": r"$\leftrightarrow$",
    "…": r"\ldots{}",
}


def _replace_unicode_outside_math(content: str) -> str:
    """Replace Unicode symbols with LaTeX commands, skipping math regions.

    Splits the content by ``$`` delimiters and only performs replacements in
    non-math segments to avoid double-wrapping like ``$α$`` → ``$$\\alpha$$``.
    """
    parts = content.split('$')
    # parts[0] is text, parts[1] is math, parts[2] is text, ...
    for i in range(0, len(parts), 2):  # even indices = outside math
        for char, replacement in _UNICODE_REPLACEMENTS.items():
            parts[i] = parts[i].replace(char, replacement)
    return '$'.join(parts)


def _fix_common_latex_issues(content: str) -> str:
    """Fix common LaTeX issues generated by LLM before compilation."""
    # Replace Unicode characters that LaTeX fonts don't support.
    # Skip characters already inside math mode ($...$) to avoid double-wrapping
    # like $α$ → $$\alpha$$ which would produce display math.
    content = _replace_unicode_outside_math(content)

    # Fix undefined math commands LLMs commonly generate
    _UNDEFINED_COMMANDS = {
        r"\arcsec": r"\mathrm{arcsec}",
        r"\arcmin": r"\mathrm{arcmin}",
        r"\dB": r"\mathrm{dB}",
        r"\Hz": r"\mathrm{Hz}",
        r"\kHz": r"\mathrm{kHz}",
        r"\MHz": r"\mathrm{MHz}",
        r"\GHz": r"\mathrm{GHz}",
    }
    for cmd, repl in _UNDEFINED_COMMANDS.items():
        content = re.sub(re.escape(cmd) + r'(?![a-zA-Z])', lambda _: repl, content)

    # Fix enumitem shortlabel: \begin{enumerate}[a)] -> \begin{enumerate}[label=\alph*)]
    content = re.sub(
        r'\\begin\{enumerate\}\[a\)\]',
        r'\\begin{enumerate}[label=\\alph*)]',
        content,
    )
    content = re.sub(
        r'\\begin\{enumerate\}\[A\)\]',
        r'\\begin{enumerate}[label=\\Alph*)]',
        content,
    )
    content = re.sub(
        r'\\begin\{enumerate\}\[i\)\]',
        r'\\begin{enumerate}[label=\\roman*)]',
        content,
    )
    content = re.sub(
        r'\\begin\{enumerate\}\[I\)\]',
        r'\\begin{enumerate}[label=\\Roman*)]',
        content,
    )
    # Fix \begin{enumerate}[1)] and similar
    content = re.sub(
        r'\\begin\{enumerate\}\[1\)\]',
        r'\\begin{enumerate}[label=\\arabic*)]',
        content,
    )
    content = re.sub(
        r'\\begin\{enumerate\}\[1\.\]',
        r'\\begin{enumerate}[label=\\arabic*.]',
        content,
    )

    # Fix \centering inside tabularx X columns: \centering redefines \\
    # to \newline, which breaks \hline after \\. Add \arraybackslash to
    # restore \\ as row-end. Only apply inside tabularx environments.
    content = _fix_centering_in_tabularx(content)

    # Fix "There's no line here to end": font-only group followed by \\
    # e.g. {\fontsize{...}\selectfont\heiti\bfseries }\\[1em]
    # When Jinja2 variables render empty, only font commands remain.
    # Insert ~ before closing } so \\ has content to end.
    content = re.sub(
        r'(\\(?:bfseries|normalfont|itshape|mdseries|selectfont|heiti|songti|fangsong|kaiti))\s*\}(\\\\)',
        r'\1~}\2',
        content,
    )

    # Replace CJK font names with current platform's available fonts
    content = _remap_cjk_fonts(content)

    # When using bundled FandolFonts as fallback, rewrite font commands to use
    # Path=./ so fontspec loads them from the build dir (MiKTeX ignores OSFONTDIR)
    content = _rewrite_fandol_with_path(content)

    # Deduplicate \label{} to prevent "multiply-defined labels" errors
    content = _dedup_labels(content)

    # Fix truncated LaTeX: close unclosed environments and ensure \end{document}
    content = _fix_truncated_latex(content)

    return content


def _remap_cjk_fonts(content: str) -> str:
    """Delegate to the shared ``remap_cjk_fonts`` in the fonts package."""
    from app.core.fonts import remap_cjk_fonts
    return remap_cjk_fonts(content)


# Fandol family name → (regular filename, bold filename or None)
_FANDOL_FILES: dict[str, tuple[str, str | None]] = {
    "FandolSong": ("FandolSong-Regular.otf", "FandolSong-Bold.otf"),
    "FandolHei": ("FandolHei-Regular.otf", "FandolHei-Bold.otf"),
    "FandolKai": ("FandolKai-Regular.otf", None),
    "FandolFang": ("FandolFang-Regular.otf", None),
}


def _rewrite_fandol_with_path(content: str) -> str:
    """Add ``Path=./`` to Fandol font commands for MiKTeX compatibility.

    MiKTeX ignores the ``OSFONTDIR`` env var (a kpathsea / TeX Live feature),
    so bundled FandolFonts copied to the build directory must be loaded via
    fontspec's ``Path`` option.  Only rewrites when the current platform is
    using FandolFonts as fallback.
    """
    from app.core.fonts import get_cjk_fonts

    if not get_cjk_fonts().is_fallback:
        return content

    pattern = re.compile(
        r'(\\(?:setCJK(?:main|sans|mono)font'
        r'|newCJKfontfamily\s*\\[a-zA-Z]+'
        r'|setCJKfamilyfont\s*\{[^}]*\}))'
        r'(?:\s*\[([^\]]*)\])?\s*\{(Fandol(?:Song|Hei|Kai|Fang))\}'
    )

    def _rewrite(m: re.Match) -> str:
        cmd, options, family = m.group(1), m.group(2) or "", m.group(3)
        files = _FANDOL_FILES.get(family)
        if not files or "Path=" in options:
            return m.group(0)

        regular, bold = files
        new_parts = ["Path=./"]

        if options:
            # Replace Fandol family names in BoldFont= with bold filenames
            for fam, (reg, bld) in _FANDOL_FILES.items():
                options = re.sub(
                    r'(BoldFont\s*=\s*)' + re.escape(fam),
                    r'\g<1>' + (bld or reg), options,
                )
            # Add BoldFont if not already specified and bold variant exists
            if bold and "BoldFont" not in options:
                new_parts.append(f"BoldFont={bold}")
            new_parts.append(options)
        elif bold:
            new_parts.append(f"BoldFont={bold}")

        return f"{cmd}[{','.join(new_parts)}]{{{regular}}}"

    return pattern.sub(_rewrite, content)


def _ensure_bundled_fonts(build_dir: Path) -> None:
    """Copy bundled FandolFonts to *build_dir* when the platform uses them."""
    from app.core.fonts import get_cjk_fonts, get_bundled_fonts_dir

    if not get_cjk_fonts().is_fallback:
        return

    bundled = get_bundled_fonts_dir()
    if not bundled.is_dir():
        return

    for otf in bundled.glob("*.otf"):
        dest = build_dir / otf.name
        if not dest.exists():
            shutil.copy2(otf, dest)



_DEDUP_SUFFIX = '__dup'


def _dedup_labels(content: str) -> str:
    """Detect duplicate \\label{} and auto-suffix to prevent LaTeX errors.

    Uses a distinctive ``__dup`` suffix so that repeated calls are idempotent:
    previous dedup suffixes are stripped before re-scanning.
    """
    # Strip previous dedup suffixes to make the function idempotent
    content = re.sub(
        r'\\label\{([^}]+?)' + re.escape(_DEDUP_SUFFIX) + r'\d+\}',
        lambda m: f'\\label{{{m.group(1)}}}',
        content,
    )

    seen: dict[str, int] = {}

    def replace_label(m: re.Match) -> str:
        label = m.group(1)
        seen[label] = seen.get(label, 0) + 1
        if seen[label] == 1:
            return m.group(0)
        return f'\\label{{{label}{_DEDUP_SUFFIX}{seen[label]}}}'

    return re.sub(r'\\label\{([^}]+)\}', replace_label, content)


def _fix_centering_in_tabularx(content: str) -> str:
    """Fix \\centering inside tabularx that breaks \\\\ row endings.

    In tabularx X columns (paragraph mode), \\centering redefines \\\\ to
    \\newline instead of \\tabularnewline, causing 'Misplaced \\noalign'
    errors when \\hline follows. Fix by appending \\arraybackslash after
    \\centering inside tabularx environments.
    """
    def fix_tabularx_block(m: re.Match) -> str:
        block = m.group(0)
        # Add \arraybackslash after bare \centering (not already followed by it)
        block = re.sub(
            r'\\centering(?!\\arraybackslash)',
            r'\\centering\\arraybackslash',
            block,
        )
        return block

    content = re.sub(
        r'\\begin\{tabularx\}.*?\\end\{tabularx\}',
        fix_tabularx_block,
        content,
        flags=re.DOTALL,
    )
    return content


def _fix_truncated_latex(content: str) -> str:
    """Ensure \\end{document} exists when \\begin{document} is present.

    Previously this tried to auto-close all unclosed environments by tracking
    a begin/end stack.  That approach is fragile — a simple stack cannot handle
    mismatched or nested environments correctly, and blindly appending wrong
    ``\\end{}`` tags often makes the document *worse*.  Environment mismatches
    are better left to the fix agent which can reason about context.

    Now we only guarantee that ``\\end{document}`` is present when
    ``\\begin{document}`` is found.
    """
    if _find_begin_document(content) is not None and '\\end{document}' not in content:
        content = content.rstrip() + '\n\\end{document}\n'
    return content


def _build_tex_env() -> dict[str, str]:
    """Build environment dict with TeX binaries in PATH, cross-platform.

    Also sets OSFONTDIR to include bundled FandolFonts so fontspec can
    always find CJK fallback fonts regardless of system font installation.
    """
    from app.core.fonts import get_bundled_fonts_dir

    env = {**os.environ}
    tex_bin = "/Library/TeX/texbin"
    if platform.system() != "Windows" and Path(tex_bin).is_dir():
        env["PATH"] = f"{tex_bin}{os.pathsep}{env.get('PATH', '')}"

    # Add bundled fonts to OSFONTDIR so XeTeX/fontspec can find them
    bundled = str(get_bundled_fonts_dir())
    existing = env.get("OSFONTDIR", "")
    env["OSFONTDIR"] = f"{bundled}{os.pathsep}{existing}" if existing else bundled

    return env


async def _run_subprocess(
    cmd_args: list[str],
    cwd: str,
    env: dict[str, str],
    timeout: float,
) -> tuple[int, str, str]:
    """Run a subprocess with Windows-compatible fallback.

    On Windows with SelectorEventLoop, asyncio.create_subprocess_exec raises
    NotImplementedError. Falls back to subprocess.run in a thread.
    """
    try:
        process = await asyncio.create_subprocess_exec(
            *cmd_args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=cwd,
            env=env,
        )
        stdout, stderr = await asyncio.wait_for(
            process.communicate(), timeout=timeout,
        )
        return (
            process.returncode or 0,
            stdout.decode("utf-8", errors="replace"),
            stderr.decode("utf-8", errors="replace"),
        )
    except NotImplementedError:
        logger.debug(
            "asyncio subprocess not supported on this event loop, using sync fallback"
        )
        try:
            result = await asyncio.to_thread(
                subprocess.run,
                cmd_args,
                capture_output=True,
                cwd=cwd,
                env=env,
                timeout=timeout,
            )
            return (
                result.returncode,
                result.stdout.decode("utf-8", errors="replace"),
                result.stderr.decode("utf-8", errors="replace"),
            )
        except subprocess.TimeoutExpired:
            raise asyncio.TimeoutError()


def _copy_support_dirs(support_dirs: list[Path], target_dir: Path) -> None:
    """Copy support directories (cls/sty/bst etc.) into the compilation target."""
    for src_dir in support_dirs:
        dst = target_dir / src_dir.name
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src_dir, dst)


async def compile_latex(
    latex_content: str,
    output_dir: Path,
    support_dirs: list[Path] | None = None,
) -> CompileResult:
    """Compile LaTeX content to PDF using latexmk + xelatex."""
    output_dir.mkdir(parents=True, exist_ok=True)
    if support_dirs:
        _copy_support_dirs(support_dirs, output_dir)
    _ensure_bundled_fonts(output_dir)
    latex_content = _fix_common_latex_issues(latex_content)

    tex_path = output_dir / "document.tex"
    tex_path.write_text(latex_content, encoding="utf-8")

    env = _build_tex_env()

    # `-xelatex` is a latexmk flag (select xelatex engine); when the user
    # configures LATEX_CMD to call xelatex/lualatex directly, omit it.
    is_latexmk = "latexmk" in Path(settings.LATEX_CMD).name
    cmd_args = [settings.LATEX_CMD]
    if is_latexmk:
        cmd_args.append("-xelatex")
    cmd_args += ["-synctex=1", "-interaction=nonstopmode", "-no-shell-escape", "document.tex"]
    logger.info("compile_latex: cmd=%s  cwd=%s", " ".join(cmd_args), output_dir)
    logger.debug("compile_latex: PATH=%s", env.get("PATH", ""))

    try:
        returncode, log_text, err_text = await _run_subprocess(
            cmd_args, cwd=str(output_dir), env=env, timeout=60,
        )
        full_log = log_text + "\n" + err_text

        logger.debug("compile_latex: return_code=%s  log_length=%d", returncode, len(full_log))

        pdf_path = output_dir / "document.pdf"
        if returncode == 0 and pdf_path.exists():
            logger.info("compile_latex: success, pdf=%s", pdf_path)
            return CompileResult(
                success=True,
                pdf_path=str(pdf_path),
                log=full_log,
            )

        # latexmk failed but may have produced a PDF with partial content.
        # Record the mtime BEFORE writing .tex so we can detect stale PDFs.
        errors = _extract_errors(full_log)
        if pdf_path.exists() and tex_path.exists():
            pdf_mtime = pdf_path.stat().st_mtime
            tex_mtime = tex_path.stat().st_mtime
            if pdf_mtime >= tex_mtime:
                # PDF was updated during this run — return it with warnings
                logger.warning(
                    "compile_latex: latexmk returned %s but PDF was updated, treating as partial success. errors=%s",
                    returncode, errors[:3],
                )
                return CompileResult(
                    success=True,
                    pdf_path=str(pdf_path),
                    log=full_log,
                    errors=errors,
                )
            else:
                logger.warning(
                    "compile_latex: failed (rc=%s), PDF is stale. errors=%s",
                    returncode, errors[:5],
                )
        else:
            logger.warning("compile_latex: failed, errors=%s", errors[:5])
        logger.debug("compile_latex: full log\n%s", full_log[-3000:])
        return CompileResult(
            success=False,
            log=full_log,
            errors=errors if errors else ["PDF file was not generated."],
        )

    except asyncio.TimeoutError:
        logger.error("compile_latex: timed out (60s)  cwd=%s", output_dir)
        return CompileResult(
            success=False,
            log="Compilation timed out after 60 seconds.",
            errors=["Compilation timed out."],
        )
    except FileNotFoundError:
        logger.error("compile_latex: command not found: %s", settings.LATEX_CMD)
        return CompileResult(
            success=False,
            log=f"Command '{settings.LATEX_CMD}' not found.",
            errors=[f"LaTeX compiler '{settings.LATEX_CMD}' is not installed or not in PATH."],
        )


async def validate_latex_syntax(
    latex_content: str,
    support_dirs: list[Path] | None = None,
) -> CompileResult:
    """Quick syntax validation using xelatex -draftmode (no PDF output).

    Much faster than full compilation — only checks syntax without generating
    any output file. Used to validate individual chapters before assembly.
    """
    import tempfile

    work_dir = Path(tempfile.mkdtemp(prefix="latex_validate_"))

    try:
        if support_dirs:
            _copy_support_dirs(support_dirs, work_dir)
        _ensure_bundled_fonts(work_dir)
        latex_content = _fix_common_latex_issues(latex_content)
        tex_path = work_dir / "validate.tex"
        tex_path.write_text(latex_content, encoding="utf-8")

        env = _build_tex_env()

        cmd_args = [
            "xelatex", "-draftmode", "-interaction=nonstopmode",
            "-no-shell-escape", "-halt-on-error", "validate.tex",
        ]
        logger.info("validate_latex_syntax: cmd=%s  cwd=%s", " ".join(cmd_args), work_dir)
        logger.debug("validate_latex_syntax: PATH=%s", env.get("PATH", ""))

        try:
            returncode, log_text, err_text = await _run_subprocess(
                cmd_args, cwd=str(work_dir), env=env, timeout=30,
            )
            full_log = log_text + "\n" + err_text

            errors = _extract_errors(full_log)
            if errors:
                logger.warning("validate_latex_syntax: errors=%s", errors[:5])
            else:
                logger.debug("validate_latex_syntax: ok, return_code=%s", returncode)
            return CompileResult(
                success=returncode == 0,
                log=full_log,
                errors=errors,
            )
        except asyncio.TimeoutError:
            logger.error("validate_latex_syntax: timed out (30s)  cwd=%s", work_dir)
            return CompileResult(
                success=False,
                log="Validation timed out after 30 seconds.",
                errors=["Validation timed out."],
            )
        except FileNotFoundError:
            logger.error("validate_latex_syntax: xelatex not found in PATH")
            return CompileResult(
                success=False,
                log="xelatex not found.",
                errors=["xelatex is not installed or not in PATH."],
            )
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


def _extract_errors(log: str) -> list[str]:
    errors = []
    for line in log.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue
        # Standard TeX errors (e.g. "! Undefined control sequence.")
        if stripped.startswith("!"):
            errors.append(stripped)
        # Package/Class/LaTeX errors (e.g. "Package fontspec Error:", "LaTeX Error:")
        elif re.search(r'(?:Package|Class|LaTeX)\s+\S*\s*Error', stripped):
            errors.append(stripped)
        # Font-related failures that may lack "!" prefix
        elif "nullfont" in stripped or "not loadable" in stripped:
            errors.append(stripped)
    return errors
